# Continuous Integration workflow for deploying the blog
name: CI
run-name: $\{\{ github.actor \}\} is running CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.12.1
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: |
          # Configure npm settings
          echo 'auto-install-peers=true' >> .npmrc
          echo 'strict-peer-dependencies=false' >> .npmrc
          # Install dependencies
          pnpm install
      
      - name: Build project
        run: pnpm build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: $\{\{ secrets.GITHUB_TOKEN \}\}
          publish_dir: ./dist