name: CI
run-name: $\{\{ github.actor \}\} is running CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.12.1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          echo 'auto-install-peers=true' >> .npmrc
          pnpm install
      - name: Build project
        run: pnpm build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: $\{\{ secrets.GITHUB_TOKEN \}\}
          publish_dir: ./dist